package-lock.json
src/shared/game/player/player.ts

Use pdefer for ready up promise, check if null before resolving

---

src/app/game/lobbyStage.tsx
src/app/store/actions/gameActions.ts
src/app/store/actiontypes/gameActionTypes.ts
src/app/store/reducers/gameReducer.ts
src/app/store/sagas/actions/networking.ts
src/app/style/components/_lobby.scss
src/server/server.ts
src/shared/packet-opcodes.ts

Add Play Solo mode

---

src/app/game/menuStage.tsx
src/app/style/components/_menu.scss

Add How To Play

---

src/shared/board/reducers/piecePositionsReducer.test.ts
src/shared/board/reducers/piecePositionsReducer.ts

Remove dead pieces positions on the board

---

src/app/display/style/components/_feed.scss
src/app/display/style/components/_player-list.scss
src/app/display/style/globals/_colors.scss
src/app/features/feed/feed.tsx
src/app/features/feed/feedMessagesReducer.ts
src/app/features/playerList/battleInfo.tsx
src/app/features/playerList/playerList.tsx
src/app/features/playerList/playerListItem.tsx
src/app/features/playerList/playerName.tsx
src/app/store/playerSelectors.ts
src/shared/game/game.ts
src/shared/game/player/player.ts
src/shared/game/playerList.ts
src/shared/models/feed-message.ts
src/shared/models/player-list-player.ts

Show player battle status in player list

---

src/app/display/profile/pieceCount.tsx
src/app/display/profile/profile.tsx
src/app/display/stages/gameStage.tsx
src/app/display/style/components/_profile.scss

Add piece count warning

---

src/shared/game/player/bot.ts
src/shared/match/combat/battleEventChannel.ts
src/shared/match/combat/movement.ts
src/shared/match/combat/pathfinding.ts
src/shared/match/combat/turnSimulator.ts
src/shared/player/pieceSelectors.ts
src/shared/player/sagas/dropPiece.ts
src/shared/utils/get-total-health-by-team.ts
src/shared/utils/is-a-team-defeated.ts

This should make the battle logic significantly quicker as the lookups are using the index objects rather than iterating.

Use BoardState in battle logic

---

package.json
src/benchmark/balancing/set-stages.ts
src/benchmark/battle.ts
src/shared/game/definitions/definitionClass.ts
src/shared/match/combat/turnSimulator.ts
src/shared/utils/get-type-attack-bonus.ts
tsconfig.json

Do some creature balancing based on hidden rules 😄

Balance creatures

---

.github/workflows/deploy-to-gh-pages.yml
packages/app/privacy.html
packages/app/src/auth/LoginPage.tsx
packages/app/src/display/footer.tsx
packages/app/src/display/game/help.tsx
packages/app/src/display/stages/gameStage.tsx
packages/app/src/display/stages/lobbyStage.tsx
packages/app/src/display/stages/menuStage.tsx

Add privacy policy

---

packages/app/index.ejs
packages/app/privacy.html
packages/app/webpack.config.js

Install Cookiebot for cookie consent

---

packages/app/src/networking/saga.ts
packages/server/src/connection.ts
packages/shared/game/events/eventManager.ts
packages/shared/game/game.ts
packages/shared/game/playerList.ts

Close sockets and tear down game at end

---

packages/app/src/auth/CallbackPage.tsx
packages/app/src/auth/store/saga.ts
packages/app/src/display/game/mobileGame.tsx
packages/app/src/display/game/settings/quitGameButton.tsx
packages/app/src/display/game/settings/settings.tsx
packages/app/src/display/stages/gameStage.tsx
packages/app/src/display/style/components/_player-list.scss
packages/app/src/display/style/components/mobile/_.scss
packages/app/src/display/style/components/mobile/_settings.scss
packages/app/src/features/playerList/playerList.tsx
packages/app/src/features/playerList/playerListItem.tsx
packages/app/src/overlay.ts
packages/app/src/store/sagas/actions/preventAccidentalClose.ts
packages/models/index.ts
packages/models/player-list-player.ts
packages/server/src/connection.ts
packages/server/src/server.ts
packages/shared/game/game.ts
packages/shared/game/player/player.ts
packages/shared/game/playerList.ts
packages/shared/game/plugins/matchRewards.ts
packages/shared/player/actions.ts

Allow user to resign from a game

---

jest.config.base.js
packages/app/src/auth/config.ts
packages/app/src/auth/index.ts
packages/app/src/game/index.ts
packages/app/src/game/sagas/index.ts
packages/app/src/game/sagas/networking/incoming.ts
packages/app/src/game/sagas/networking/outgoing.ts
packages/app/src/game/sagas/networking/saga.ts
packages/app/src/lobby/lobbyPage.tsx
packages/app/src/lobby/networking.ts
packages/app/src/lobby/store/actions.ts
packages/app/src/menu/findGame.ts
packages/app/src/menu/menuPage.tsx
packages/app/src/store/saga.ts
packages/app/src/ui/socket.ts
packages/server-game/src/matchmaking/lobby/lobby.ts
packages/server-game/src/player/socket/net/incoming.ts
packages/server-game/src/player/socket/socketPlayer.ts
packages/shared/.gitignore
packages/shared/jest.config.js
packages/shared/src/game/player/player.ts
packages/shared/src/index.ts
packages/shared/src/networking/client-to-server.ts
packages/shared/src/networking/index.ts
packages/shared/src/networking/server-to-client-lobby.ts
packages/shared/src/networking/server-to-client-menu.ts

fix: Fix networking for player actions

---

packages/app/src/game/sagas/networking/incoming.ts
packages/shared/src/networking/server-to-client.ts

fix: Emit round information when entering preparing phase

---

packages/shared/src/game/player/bench/reducers/piecesReducer.ts
packages/shared/src/game/player/pieceSelectors.ts

fix: Limit player to 7 bench pieces

---

README.md
packages/app/src/index.tsx
packages/app/src/menu/auth/config.ts
packages/auth-server/src/verifyDecodeJwt.ts
packages/server-game/src/server.ts
packages/server-info/src/index.ts
packages/shared/src/config.live.ts
packages/shared/src/config.local.ts
packages/shared/src/config.ts
packages/shared/src/environment.ts
packages/shared/src/index.ts

Might want to read `environment` from an env variable, rather than fiddling with it in another file also.

Hardcode less config

---

packages/gamemode/src/game/gameLoop/index.ts

closes #382 
* fixed bug where player can win after dying
* changed function from getAll to getLiving

fix: Player can win after dying

---

packages/gamemode/src/entities/player/sagas/matchRewards.ts
packages/gamemode/src/entities/player/state/playerInfo/reducer.ts
packages/gamemode/src/game/playerPropertyUpdates.ts
packages/models/src/index.ts
packages/models/src/playerStreak.ts

close #425
Moved PlayerStreak interface to models package and updated imports accordingly.

Moved PlayerStreak to @models package

---

packages/app/src/game/state.ts
packages/gamemode/src/entities/player/state/index.ts
packages/gamemode/src/game/index.ts
packages/gamemode/src/game/roundInfo/index.ts
packages/gamemode/src/game/roundInfo/state.ts
packages/gamemode/src/game/store.ts
packages/gamemode/src/index.ts
packages/models/src/index.ts
packages/models/src/roundInfoState.ts
packages/networking/src/server-to-client/server-to-client-game.ts
packages/server-game/src/player/socket/net/reconnect.ts

close #430 
* Moved RoundInfoState type to models package and updated imports accordingly.

Moved RoundInfoState to models package

---

packages/app/src/display/style/components/ui/_overlay.scss
packages/app/src/game/module/board/boardContainer.tsx
packages/app/src/game/module/board/overlays/spectatingOverlay.tsx
packages/app/src/game/module/board/responsiveBoardStyles.tsx

Added overlay when user is spectating another player which takes the place of the bench. Gives the name of who is being spectated plus a button to stop spectating. Responsive to screen width.
closes #422

Spectating overlay

---

packages/app/src/game/components/piece/interactablePiece.tsx
packages/app/src/game/module/board/index.ts
packages/app/src/game/module/board/sagas/clickPieceSaga.ts
packages/app/src/game/module/board/sagas/clickTileSaga.ts
packages/app/src/game/module/board/tileInteraction.ts
packages/app/src/game/module/index.ts
packages/app/src/game/sagas/index.ts
packages/app/src/game/ui/index.ts
packages/gamemode/src/playerActions/dropPiece.ts
packages/gamemode/src/playerActions/index.ts
packages/gamemode/src/playerActions/saga.ts
packages/gamemode/src/playerActions/swapPiece.ts
packages/server-game/src/player/socket/board/subscribeToBoard.ts
packages/shoki-board-react/src/components/BoardGrid.tsx
packages/shoki-board-react/src/components/tile/DroppableTile.tsx
packages/shoki-board-react/src/components/tile/UndroppableTile.tsx
packages/shoki-board/src/state.ts

feat: piece swapping

---

apps/web-game/src/game/board/BoardContainer.tsx
apps/web-game/src/game/board/overlays/controls/Controls.tsx
apps/web-game/src/game/board/overlays/controls/ReadyUpButton.tsx
apps/web-game/src/game/board/overlays/controls/SellPieceButton.tsx
apps/web-game/src/game/board/overlays/controls/colors.ts
apps/web-game/src/game/board/overlays/index.ts
apps/web-game/src/game/layouts/mobile/MobileGame.stories.tsx

feat: reimplement sell piece button

---

.github/workflows/deploy-to-gh-pages.yml
apps/web-game/src/game/board/hooks/renderPiece.tsx
apps/web-game/src/game/layouts/mobile/MobileGame.tsx
apps/web-game/webpack.config.js
apps/web-menu/webpack.config.js
docker-compose.yml
modules/@creature-chess/auth-web/config.ts
modules/@creature-chess/ui/gameBoard/GameBoard.tsx
terraform/main.tf
terraform/modules/server_game/ecs.tf
terraform/modules/server_game/task_definitions.json.tpl
terraform/modules/server_game/variables.tf
terraform/variables.tf

Updated APP_KEY env variable to match the readme's: CREATURE_CHESS_APP_URL

refactor: prefix APP_KEY env variable with CREATURE_CHESS_

---

README.md
apps/nodejs-builder.Dockerfile

Changes from yarn berry to 3.4.1.

chore: changing yarn version from berry to 3.4.1

---

modules/@creature-chess/gamemode/src/playerActions/index.ts

fix: sync swapPiecePlayerAction
